### ISSUE TITLE
Unclear why layout did not converge within 5 attempts

### ISSUE THREAD

**Issue by pvelayudhan** [touying-typ/touying#72]
Hello,

Thank you for all the amazing recent updates you have made!

I am finding that some slides I am preparing with a combination of pauses and figures have been returning the `warning: layout did not converge within 5 attempts` message and am not exactly sure why that is. 

Here is a MWE that results in this issue:

```
#import "@preview/touying:0.5.2": *
#import themes.dewdrop: *
#show: dewdrop-theme

= A

#figure(image("square.svg", height: 40%))

#pause 1

= B

2 #pause

= C
```

I've attached square.svg as a file here:
 
![square](https://github.com/user-attachments/assets/298d9a09-d959-4e0b-9331-55c9802af9ee)

For whatever reason, any of the following adjustments renders the slides without any problems:

1. Removing the figure
2. Removing either of the lines containing pauses
3. Removing section headers B or C

Any insight as to what I may be doing wrong here or how to avoid this would be greatly appreciated!

**Comment by OrangeX4** [comment]
This will be fixed in typst 0.12 and you can fix it by `config-common(enable-frozen-states-and-counters: false)` for now.

**Comment by pvelayudhan** [comment]
Great to hear and that did fix it, thank you!

**Comment by OrangeX4** [comment]
This issue should have been fixed in Typst 0.12 and I'll close this issue.

**Comment by nycex** [comment]
I do still have an (at least similar) issue with typst `0.12.0`:

```typst
#import "@preview/touying:0.5.3": *
#import themes.metropolis: *

#show: metropolis-theme.with(
  // config-common(enable-frozen-states-and-counters: false)
)

#figure(
  "B",
)
#pause

- U

#pagebreak()

+ V
#pause

W

#pagebreak()

Y
#pause
Z

```


Here, I also get a `layout did not converge within 5 attempts` that is _fixed_ by `config-common(enable-frozen-states-and-counters: false)`.

**Comment by aparatext** [comment]
I had the same issue in my presentation. typst 0.14.2, touying 0.7.0.

`enable-frozen-states-and-counters: false` fixed that.

**Comment by hashcatHitman** [comment]
Seems like the same issue for me too. Typst 0.14.2, touying 0.7.3. Minimal example included.

```typst
#import "@preview/touying:0.7.3": *
#import themes.simple: *
#show: simple-theme

#slide[
  #pause
][
  #figure(
    none, // This could have content, it doesn't seem to matter
  )
]
#pause
#pagebreak() // This could also be `=`, `==`, or `---`
#pause
#pagebreak() // This could also be `=`, `==`, or `---`
#pause
```

**Comment by Sky-NiniKo** [comment]
Same and it causes rendering issues:
```typ
#import "@preview/touying:0.7.4": *
#show: touying-slides

#pause
#figure(
  none // This could have content, it doesn't seem to matter
)

#pagebreak() // This could also be `=`, `==`, or `---`
#pause

#pagebreak() // This could also be `=`, `==`, or `---`
#pause

#pagebreak() // This could also be `=`, `==`, or `---`
#pause

#figure(
  none, // This could have content, it doesn't seem to matter
  caption: [Should be \#2. Numbering issue here]
)
```
Using Typst 0.15.1 and touying 0.7.4
